name: CI

on:
  schedule:
    - cron: '30 11 * * *'

jobs:
  deploy:
    runs-on: self-hosted

    env:
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
      SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: create store proc from file
        run: |
          NAME=`curl https://www.pseudorandom.name/`
          ~/bin/snowsql -f ./querytest.sql --variable NAME="$NAME"
#          ~/bin/snowsql -q "insert into testname (name) values('namesecond')"
      # Runs a single command using the runners shell
#      - name: Upload artifact to SnowSQL
#        run: |
#          ~/bin/snowsql -q 'put file://'$(pwd)'/storedproc.py @~/${{ github.ref_name }} overwrite=true' -o friendly=false
#      - name: create store proc from file
#        run: |
#          ~/bin/snowsql -q 'CREATE OR REPLACE PROCEDURE plus_by_one(INPUT_INT int)
#          returns int not null
#          language python
#          runtime_version = '\''3.8'\''
#          packages = ('\''snowflake-snowpark-python'\'')
#          imports = ('\''@~/${{ github.ref_name }}/storedproc.py'\'')
#          handler = '\''storedproc.run'\'';'
#      - name: Create or update storedproc
#        run: |
#          ~/bin/snowsql -q 'CREATE OR REPLACE PROCEDURE multiply_integer_by_three(INPUT_INT int)
#            returns int not null
#            language python
#            runtime_version = '\''3.8'\''
#            packages = ('\''snowflake-snowpark-python'\'')
#            handler = '\''multiply_by_three_py'\''
#          as
#          $$
#          def multiply_by_three_py(snowpark_session, input_int_py: int):
#            return input_int_py*3
#          $$
#          ;'
